//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NoscovSchoolEntities3 : DbContext
    {
        private static NoscovSchoolEntities3 _context;
        public NoscovSchoolEntities3()
            : base("name=NoscovSchoolEntities3")
        {
        }

        public static NoscovSchoolEntities3 GetContext()
        {
            if (_context == null)
                _context = new NoscovSchoolEntities3();

            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Manufacture> Manufactures { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSale> ProductSales { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
