//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealPageApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int ID { get; set; }
        public Nullable<int> AgrementID { get; set; }
        public Nullable<int> DealTypeID { get; set; }
        public Nullable<int> DealKindID { get; set; }
        public Nullable<int> DealPlaceID { get; set; }
        public Nullable<int> CalculationID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> TikerID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Constractor { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> DealDate { get; set; }
        public Nullable<int> Quanity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string Trader { get; set; }
        public Nullable<decimal> CommisionExchange { get; set; }
        public string Note { get; set; }
    
        public virtual Agreement Agreement { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual DealKind DealKind { get; set; }
        public virtual DealPlace DealPlace { get; set; }
        public virtual DealType DealType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
        public virtual Tiker Tiker { get; set; }
    }
}
